server:
  port: 8080

greeting:
  welcome: You are using ${spring.application.name}.

logging:
  #  file:
  #    path: /var/logs/
  #    file: TacoCloud.log
  level:
    root: INFO
    org.springframework.security: INFO

spring:
  application:
    name: taco-cloud-application
  datasource:
    #    initialization-mode: never
    #    generate-unique-name: false
    name: taco-cloud
    url: jdbc:h2:mem:taco-cloud
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true # if there is a data.sql it will be applied after the schema generation by jpa
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  rabbitmq:
    template:
      exchange: tacocloud.order
      routing-key: kitchens.central
      receive-timeout: 30000
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
  sql:
    init:
      mode: never # don't run the default scripts and let jpa create from java classes
  thymeleaf:
    cache: false

taco:
  orders:
    pageSize: 10

---
spring:
  config:
    activate:
      on-profile: qa

taco:
  orders:
    pageSize: 15
